config/routes.rb
Rails.application.routes.draw do
  root to: '/', to: 'fluxes#index'
  resources :fluxes, only: ['index', 'new', 'create'] do
    get 'articles', to: 'articles#index'
    post 'articles/new', to: 'articles#new'
    get '/articles/read', to: 'articles#read'
    get '/articles/unread', to: 'articles#unread'
  end
  get '/fluxes/actu', to: 'fluxes#actu'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :flux
end

app/models/flux.rb
class Flux < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :Title, presence: true
  validates :Title, uniqueness: true
  validates :Url, presence: true
  validates :Url, format: { with: /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/,
    message: "désolé ce n'est pas le bon format" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
require 'rubygems'
require 'simple-rss'
require 'open-uri'
require 'date'


class ArticlesController < ApplicationController

  def index
    @articles_no_order = Article.where(flux_id: params[:flux_id])
    @articles = order_by_date(@articles_no_order)
    render json: @articles
  end

  def new
    @flux = Flux.find(params[:flux_id])
    @array_items = call(@flux)
    @first = @array_items.first
    calculator = 0
    @flux.articles.each do |article|
      if article.Publication == @first.pubDate.to_s
        calculator += 1
      else
        calculator += 0
      end
    end
    if calculator == 0
      @article = Article.new
      @article.Title = @first.title
      @article.Description = @first.description
      @article.Url = @first.link
      @article.Publication = @first.pubDate
      @article.flux_id = @flux.id
      if @article.save
        @articles_no_order = @flux.articles
        @articles = order_by_date(@articles_no_order)
        render json: @articles
      else
        render json: 0
      end
    else
      render json: 0
    end
  end

  def read
    @fluxes = Flux.all
    @article = Article.find(params[:id])
    @article.Lu = true
    @flux = Flux.find(@article.flux_id)
    if @article.save
      render json: @article
    else
      redirect_to fluxes_path(@fluxes)
    end
  end

  def unread
    @fluxes = Flux.all
    @article = Article.find(params[:id])
    @article.Lu = false
    if @article.save
      render json: @article
    else
      redirect_to fluxes_path(@fluxes)
    end
  end

  private

  def call(flux)
    url = @flux.Url
    rss = SimpleRSS.parse open(url)
    @array_items = []
    rss.channel.items.each do |item|
      @array_items << item
    end
    return @array_items
  end

  def order_by_date(articles)
    my_hash = {}
    articles.each do |article|
      d = DateTime.parse(article.Publication)
      date = DateTime.new(d.year,d.month,d.day,d.hour,d.min,d.sec,d.zone).ajd.to_f
      my_hash[date] = article
    end
    sort = my_hash.sort{|a,z|z<=>a}.to_h
    @articles = []
    sort.each do |key, value|
      @articles << value
    end
    @articles
  end
end

app/controllers/fluxes_controller.rb
class FluxesController < ApplicationController

  def index
    @fluxes = Flux.all.order(created_at: params[:order] || :desc)
  end

  def create
    @fluxes = Flux.all
    @flux = Flux.new(flux_params)
    if @flux.save
      @newarticles = ArticlesCreation.new(@flux).research
      render json: @flux
    else
      respond_to do |format|
        format.html { redirect_to fluxes_path(@fluxes) }
      end
    end
  end

  private

  def flux_params
    params.require(:flux).permit(:Url, :Title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_show.html.erb
<li id="<%= article.id %>">
    <div class="content">
      <p><%= article.Title %></p>
      <p><%= article.Description %></p>
      <a href="<%= article.Url %>" target="_blank" data="<%= article.id %>">Voir l'article <i class="fas fa-arrow-right"></i></a>
      <div id="switchlu" class="display">
        <% if article.Lu == 0 %>
          <%= link_to "Afficher comme Lu", articles_read_path(id: article.id), :remote => true %>
        <% else %>
          <p><i class="fas fa-check"></i>Lu</p>
          <%= link_to "Afficher comme non Lu", articles_unread_path(id: article.id), :remote => true %>
        <% end %>
      </div>
    </div>
</li>

app/views/fluxes/_show.html.erb
<div class="col-6">
  <div class="card">
    <div class="title">
      <h2><%= flux.Title %></h2>
    </div>
    <ul class="card-overflow" id="flux<%= flux.id %>">
      <% flux.articles.each do |article| %>
        <%= render 'articles/show', article: article %>
      <% end %>
    </ul>
  </div>
</div>

app/views/fluxes/index.html.erb
<%= react_component 'Page', fluxes: @fluxes %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <noscript>
      You need to enable Javascript to run this app
    </noscript>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>